[package]
name = "timely_state"
version = "0.1.0"
authors = ["Matthew Brookes <mbrookes1304@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.1.2"
faster-rs = { git = "https://github.com/faster-rs/faster-rs", branch = "master" }
tempfile = "3"
